spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:jurisapoio_dev}
    username: ${DB_USERNAME:jurisapoio}
    password: ${DB_PASSWORD:jurisapoio}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false

jwt:
  segredo: ${JWT_SEGREDO:ZGV2U2VncmVkb0Jhc2U2NE5hb1VzYXJFbVByb2R1Y2FvMTIzNDU2Nzg=}
  expiracao-ms: 86400000

logging:
  level:
    br.edu.ufvjm.jurisapoio: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
